os: linux
language: generic
sudo: required
addons:
  apt:
    sources: &common_sources
      - deadsnakes
      - sourceline: 'ppa:kalakris/cmake'
    packages: &common_packages
      - cmake
      - time
script:
  - echo "cats"
  - cat /etc/apt/sources.list
  - ls /etc/apt/sources.list.d/
  - echo "yay"
after_script:
  - cat /etc/apt/sources.list
jobs:
  include:
    - addons:
      apt:
        sources:
          - *common_sources
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          - gammu
        packages:
          - *common_packages
          - cowsay
    - addons:
      apt:
        sources:
           - *common_sources
        packages:
           - *common_packages
           - gcc-4.8
           - varnish
    - addons:
      apt:
        sources:
          - gammu
        packages:
          - cowsay
    after_install:
      - cowsay "yay"
