os: osx
language: objective-c
osx_image: xcode9.4.1
script:
  - echo "look at how evil I am"
  - uname -a
  - sw_vers
  - xcodebuild -version
  - xcrun simctl list
  - xcrun simctl list pairs
  - df -h /
  - brew list --versions
  - brew cask list --versions
  - nvm list
  - rvm list
  - pod --version
