language: node_js

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nvm install stable

script:
  - nvm install stable
  - nvm install ${TRAVIS_NODE_VERSION}

matrix:
  include:
    - node_js: "6"
      env: ENV=node
