os: linux
language: generic
sudo: required
addons:
  apt:
    sources: &common_sources
      - ubuntu-toolchain-r-test
      - lucid
    packages: &common_packages
      - fortune
script:
  - echo "cats"
  - printenv TRAVIS_BUILD_APT_SOURCE_WHITELIST_TRUSTY
  - echo "yay"
after_script:
  - cat /etc/apt/sources.list
  - export PATH=$PATH:/usr/games
  - fortune -s | cowsay
jobs:
  include:
    - addons:
        apt:
          sources:
            - *common_sources
            - sourceline: 'deb https://packages.chef.io/repos/apt/stable trusty main'
          packages:
            - cowsay
    - addons:
        apt:
          sources:
            - *common_sources
          packages:
            - *common_packages
            - cowsay
    - addons:
        apt:
          sources:
            - sourceline: 'deb https://packages.chef.io/repos/apt/stable trusty main'
          packages:
            - cowsay
