os: linux
language: generic
sudo: required
addons:
  apt:
    sources: &common_sources
      - sourceline: 'deb http://packages.couchbase.com/ubuntu trusty main'
    packages: &common_packages
      - fortune
script:
  - echo "cats"
  - cat /etc/apt/sources.list
  - ls /etc/apt/sources.list.d/
  - echo "yay"
after_script:
  - cat /etc/apt/sources.list
  - export PATH=$PATH:/usr/games
  - fortune -s | cowsay
jobs:
  include:
    - addons:
        apt:
          sources:
            - *common_sources
            - sourceline: 'deb https://packages.chef.io/repos/apt/stable trusty main'
          packages:
            - cowsay
    - addons:
        apt:
          sources:
            - gammu
          packages:
            - *common_packages
            - cowsay
    - addons:
        apt:
          sources:
            - sourceline: 'deb https://packages.chef.io/repos/apt/stable trusty main'
          packages:
            - cowsay
